name: clang-tidy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: clang-tidy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install libgtest-dev clang-tidy-12

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Run clang-tidy
      working-directory: ${{github.workspace}}/build
      run: run-clang-tidy-12 .
