name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Debug",
            os: ubuntu-latest,
            build_type: "Debug",
            asan: "OFF"
          }
        - {
            name: "ASAN",
            os: ubuntu-latest,
            build_type: "Debug",
            asan: "ON",
          }

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install libgtest-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} -DASAN=${{matrix.config.asan}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.config.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.matrix.config.build_type}}

  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install libgtest-dev clang-tidy-12

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Run clang-tidy
      working-directory: ${{github.workspace}}/build
      run: run-clang-tidy-12 .
